name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - darwin
        goarch:
          - amd64

    steps:
    - name: Tag name
      id: tag_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Set up Go 1.13
      uses: actions/setup-go@v2 
      with:
        go-version: 1.13.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags '-extldflags "-static" -X github.com/laszlocph/woodpecker/version.Version=${{ steps.tag_name.outputs.SOURCE_TAG }}' -o bin/drone-server github.com/laszlocph/woodpecker/cmd/drone-server
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags '-X github.com/laszlocph/woodpecker/version.Version=${{ steps.tag_name.outputs.SOURCE_TAG }}' -o bin/drone-agent github.com/laszlocph/woodpecker/cmd/drone-agent
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags '-X main.version=${{ steps.tag_name.outputs.SOURCE_TAG }}' -o bin/drone cli/drone/main.go
        tar -zcvf woodpecker-"${GITHUB_REF#refs/tags/}".${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz bin/drone*

    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: ./woodpecker-${{ steps.tag_name.outputs.SOURCE_TAG }}.${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
